// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASvhZndmEEmSAO5X-7JFeExwQHINA3je8',
    appId: '1:685604832151:web:e66c47f8aaf6c86a05bad2',
    messagingSenderId: '685604832151',
    projectId: 'unitymeet-3f19b',
    authDomain: 'unitymeet-3f19b.firebaseapp.com',
    storageBucket: 'unitymeet-3f19b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKZPLTk2HxbiFEly_zwiUoXEaLxruyeYU',
    appId: '1:685604832151:android:3aca2bb7fc74a3f705bad2',
    messagingSenderId: '685604832151',
    projectId: 'unitymeet-3f19b',
    storageBucket: 'unitymeet-3f19b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSE6MmMnkNRo5VOAS20kxzXc-MhkVd9S0',
    appId: '1:685604832151:ios:ba85cb362e6e0aae05bad2',
    messagingSenderId: '685604832151',
    projectId: 'unitymeet-3f19b',
    storageBucket: 'unitymeet-3f19b.appspot.com',
    androidClientId: '685604832151-c52vfmqnsvr7r4n564de4fvjpp6r9939.apps.googleusercontent.com',
    iosClientId: '685604832151-pm14piua3k0el75u3blj9kdfsojmiflt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaloMilteHai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSE6MmMnkNRo5VOAS20kxzXc-MhkVd9S0',
    appId: '1:685604832151:ios:2567becadac85a4405bad2',
    messagingSenderId: '685604832151',
    projectId: 'unitymeet-3f19b',
    storageBucket: 'unitymeet-3f19b.appspot.com',
    androidClientId: '685604832151-c52vfmqnsvr7r4n564de4fvjpp6r9939.apps.googleusercontent.com',
    iosClientId: '685604832151-raevbamrc2fao8j91gqfji4pdpqbn87k.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaloMilteHai.RunnerTests',
  );
}
